---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
#  - ./snapshot-controller/ks.yaml
  - ./descheduler/ks.yaml
  - ./democratic-csi/ks.yaml
  - ./external-secrets/ks.yaml
  - ./nvidia-gpu-operator/ks.yaml

