# yaml-language-server: $schema=https://gist.githubusercontent.com/james-d-elliott/756de37a4398b3445072a60d674905c6/raw/ce90833b1ce145cb701184557dd964fa7546f19a/jsonschema.json
---
session:
  name: authelia_session
  same_site: lax
  expiration: 4h
  inactivity: 4h
  remember_me_duration: 1M
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.database
          port: 26379
        - host: redis-node-1.redis-headless.database
          port: 26379
        - host: redis-node-2.redis-headless.database
          port: 26379
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["radarr.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["sonarr.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["prowlarr.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["sabnzbd.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["qbittorrent.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["status.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["alertmanager.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["prometheus.${SECRET_DOMAIN}"]
      policy: two_factor
    - domain: ["echo-server.${SECRET_DOMAIN}"]
      policy: two_factor
#    - domain: ["kubernetes.${SECRET_DOMAIN}"]
#      policy: one_factor
    - domain: ["autobrr.${SECRET_DOMAIN}"]
      policy: one_factor

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: "${GRAFANA_REDIRECT_URI}"
        userinfo_signing_algorithm: none
