---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: plex-media
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  storageClassName: plex-media
  capacity:
    storage: 1Mi # Size does not matter ...twss
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.120.12
    path: /mnt/flashstor/media
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: downloads
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: media
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
