---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./kubernetes-dashboard.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./kyverno.yaml
  - ./one-password.yaml
  - ./awx.yaml
  - ./nvidia.yaml
  - ./tf-controller.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./node-feature-discovery.yaml
  - ./descheduler.yaml
  - ./democratic-csi.yaml
  - ./backube.yaml
  - ./cloudnative-pg.yaml
  - ./external-secrets.yaml
  - ./authentik.yaml
  - ./angelnu.yaml
