---
kubernetes:
  children:
    master:
      hosts:
        home-k3s-controlplane-1:
          ansible_user: a99940218
          ansible_host: 192.168.120.41
        home-k3s-controlplane-2:
          ansible_user: a99940218
          ansible_host: 192.168.120.42
        home-k3s-controlplane-3:
          ansible_user: a99940218
          ansible_host: 192.168.120.43
    worker:
      hosts:
        home-k3s-gpu-worker-1:
          ansible_user: a99940218
          ansible_host: 192.168.120.51
