apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connect-ingress
  namespace: one-password
  annotations:
    cert-manager.io/cluster-issuer: gts-production
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: "384"
spec:
  # You may need to specify the IngressClass if your cluster does not have a
  # default IngressClass, e.g. for Ingress NGINX Controller, uncomment the
  # below line:
  ingressClassName: internal
  rules:
    - host: &host connect.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: onepassword-connect
              port:
                name: connect-api
  tls:
    - hosts:
      - *host
      secretName: connect-cert
