---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName authentik
        INIT_POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: &dbPort "5432"
        INIT_POSTGRES_USER: &dbUser "{{ .AUTHENTIK_STORAGE_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .AUTHENTIK_STORAGE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        #Authentik
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_EMAIL__HOST: "{{ .AUTHENTIK_EMAIL__HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .AUTHENTIK_EMAIL__PORT }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .AUTHENTIK_EMAIL__USE_TLS }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .AUTHENTIK_EMAIL__USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .AUTHENTIK_EMAIL__PASSWORD }}"
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
        SECRET_DOMAIN: "{{ .CUSTOM_SECRET_DOMAIN }}"
        AUTHENTIK_POSTGRESQL__HOST: *dbHost
        AUTHENTIK_POSTGRESQL__NAME: *dbName
        AUTHENTIK_POSTGRESQL__USER: *dbUser
        AUTHENTIK_POSTGRESQL__PASSWORD: *dbPass
        AUTHENTIK_REDIS__URL: "redis+sentinel://redis-headless.database.svc.cluster.local:26379/?db=3&mastername=redis-master"
  dataFrom:
    - extract:
        key: Authentik
    - extract:
        key: cloudnative-pg
