---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: system-upgrade-controller
      namespace: system-upgrade
  timeout: 2m
  images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.13.1
