---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-external-db-secret
  namespace: awx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: awx-external-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        host: postgres-rw.database.svc.cluster.local
        port: '5432'
        database: awx
        username: "{{ .POSTGRES_USER }}"
        password: "{{ .POSTGRES_PASS }}"
        sslmode: prefer
        type: unmanaged
        # Postgres Init
        INIT_POSTGRES_DBNAME: awx
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: awx-db
    - extract:
        key: cloudnative-pg
