---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-db-secret
  namespace: awx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: awx-external-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # AWX
        host: &dbHost postgres-rw.database
        port: '5432'
        database: &dbName awx
        username: &dbUser "{{ .POSTGRES_USER }}"
        password: &dbPass "{{ .POSTGRES_PASS }}"
        sslmode: prefer
        type: unmanaged
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: awx-db
    - extract:
        key: cloudnative-pg
